name: Release

on:
  push:
    branches: [main]

jobs:
  docker-hub:
    name: Build and push image to docker hub
    # needs: tag
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image, tag it with latest, then push it docker hub
        uses: docker/build-push-action@v5
        with:
          tags: ghab/lenslocked:latest
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha
        # env:
        #   TAG: ${{ needs.tag.outputs.TAG }}
#   tag:
#     name: Create and push git tag
#     runs-on: ubuntu-latest
#     timeout-minutes: 5
#     outputs:
#       TAG: ${{ steps.create_tag.outputs.TAG }}
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v4

#       - name: Create CalVer tag and push it
#         id: create_tag
#         run: |
#           set -euo pipefail
#           DATE="$(date +"%Y.%m.%d")"
#           SUFFIX=1
#           TAG=$DATE
#           git config user.email "carlos.ghabrous@gmail.com  "
#           git config user.name "carlosghabrous"
#           git fetch --tags
#           until git tag "$TAG" 2> /dev/null
#           do
#               TAG="${DATE}.$((++SUFFIX))"
#           done
#           git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/carlosghabrous/lenslocked.git
#           git push --tags
#           echo "TAG=$TAG" >> "$GITHUB_OUTPUT"


